# Generated by Django 5.1.4 on 2024-12-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('skills_required', models.TextField()),
                ('career_opportunities', models.TextField()),
                ('ideal_for', models.TextField()),
                ('role_summary', models.TextField()),
            ],
        ),
    ]
