# Generated by Django 5.1.4 on 2024-12-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='ideal_for',
            new_name='skills_involved',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skills_required',
        ),
    ]
