# Generated by Django 5.1.4 on 2024-12-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0002_rename_ideal_for_skill_skills_involved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='responsibilities',
        ),
    ]
