# Generated by Django 5.1.4 on 2024-12-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0003_remove_skill_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='job_img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
