# Generated by Django 5.1.4 on 2024-12-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0004_skill_job_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
