# Generated by Django 5.1.4 on 2025-01-23 12:30

import django.db.models.deletion
import mriif.utils
import mriif.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0008_contactus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPOCRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('institute_code', models.CharField(max_length=50)),
                ('spoc_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('endorsement_letter', models.FileField(help_text='Upload signed endorsement letter from institution head (Max 5MB, Allowed formats: PDF, DOC, DOCX)', upload_to='endorsement_letters/', validators=[mriif.validators.validate_file_size, mriif.validators.validate_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_title', models.CharField(max_length=200)),
                ('institute_name', models.CharField(max_length=200)),
                ('institute_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('proposal_file', models.FileField(help_text='Upload signed endorsement letter from institution head (Max 5MB, Allowed formats: PDF, DOC, DOCX)', upload_to=mriif.utils.get_proposal_file_path, validators=[mriif.validators.validate_file_size, mriif.validators.validate_file_extension])),
                ('category', models.CharField(choices=[('CONSTRUCTION', 'Digital Construction & Design'), ('MEDIA', 'Creative Media & Digital Arts'), ('AUTOMOTIVE', 'Automotive Engineering & Technologies'), ('HEALTHCARE', 'Healthcare & Medical Technologies'), ('IT', 'IT Software Solutions for Business'), ('MECHATRONICS', 'Mechatronics & Robotics'), ('HOSPITALITY', 'Hospitality & Tourism'), ('FASHION', 'Fashion Technology & Design'), ('ELECTRONICS', 'Electronics & Electrical Engineering'), ('SUSTAINABILITY', 'Sustainability & Green Technologies'), ('AGRICULTURE', 'Agriculture & Agribusiness'), ('EDUCATION', 'Education & Training Technologies'), ('LOGISTICS', 'Logistics & Supply Chain Management'), ('DESIGN', 'Design & Innovation'), ('CYBERSECURITY', 'Cybersecurity & Digital Forensics')], max_length=20)),
                ('team_name', models.CharField(max_length=100)),
                ('student1_name', models.CharField(max_length=100)),
                ('student1_email', models.EmailField(max_length=254)),
                ('student2_name', models.CharField(max_length=100)),
                ('student2_email', models.EmailField(max_length=254)),
                ('student3_name', models.CharField(max_length=100)),
                ('student3_email', models.EmailField(max_length=254)),
                ('student4_name', models.CharField(max_length=100)),
                ('student4_email', models.EmailField(max_length=254)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
