# Generated by Django 5.1.4 on 2025-02-05 08:31

import mriif.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0009_spocregistration_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('linkedin_url', models.URLField(blank=True)),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('expertise', models.JSONField()),
                ('cv_file', models.FileField(help_text='Upload your CV (Max 5MB, Allowed formats: PDF, DOC, DOCX)', upload_to='evaluator_cvs/', validators=[mriif.validators.validate_file_size, mriif.validators.validate_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
