# Generated by Django 5.1.4 on 2025-04-15 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0010_evaluatorregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('FDP', 'Faculty Development Program'), ('RTP', 'Refresher Training Program'), ('ORT', 'Online Refresher Training'), ('SBP', 'Semester Blended Program'), ('LTP', 'Long term Program')], max_length=20)),
                ('delivery_mode', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('BLENDED', 'Blended')], max_length=20)),
                ('duration_weeks', models.IntegerField()),
                ('training_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('residential_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nsdc_share_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('mrei_share_percentage', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('requires_industry_cert', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mriif.skill')),
            ],
            options={
                'unique_together': {('course_type', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('include_residential', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mriif.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
