# Generated by Django 5.1.4 on 2025-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0011_course_courseapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='cf_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
