# Generated by Django 5.1.4 on 2025-05-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0013_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='traffic_source',
            field=models.CharField(blank=True, help_text='Source of the enquiry (e.g., Google, Facebook, Direct)', max_length=100, null=True),
        ),
    ]
