# Generated by Django 5.1.4 on 2025-05-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mriif', '0014_enquiry_traffic_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='how_did_you_hear',
            field=models.CharField(blank=True, choices=[('SEARCH', 'Search Engine'), ('SOCIAL', 'Social Media'), ('FRIEND', 'Friend or Colleague'), ('EVENT', 'Event or Workshop'), ('ADVERTISEMENT', 'Advertisement'), ('COLLEGE', 'College/University'), ('OTHER', 'Other')], help_text='How did you hear about us?', max_length=20, null=True),
        ),
    ]
